fix: don't mind how many folders are between .tox and .site-packages
From GitHub Actions:

    ```
    Run tox -e coverage-report
    coverage-report: install_deps> python -I -m pip install 'coverage[toml]'
    coverage-report: freeze> python -m pip freeze --all
    coverage-report: coverage==7.3.4,pip==23.3.1,setuptools==69.0.2,tomli==2.0.1,wheel==0.42.0
    coverage-report: commands[0]> coverage combine
    Combined data file .coverage.fv-az1116-506.1828.XNaBMOPx
    coverage-report: commands[1]> coverage xml
    No source for code: '/home/runner/work/commercetools-python-sdk/commercetools-python-sdk/.tox/py310/lib/python3.10/site-packages/commercetools/__init__.py'.
    coverage-report: exit 1 (0.19 seconds) /home/runner/work/commercetools-python-sdk/commercetools-python-sdk> coverage xml pid=1847
      coverage-report: FAIL code 1 (2.56=setup[2.25]+cmd[0.12,0.19] seconds)
      evaluation failed :( (3.03 seconds)
    Error: Process completed with exit code 1.
    ```

This commit hypothesizes that coverage.py is unable to find the source
file because the `*` glob may not cover the `py310/lib/python3.10/` in
between the directories `.tox/` and `site-packages/`.